apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/B-O-W/EKS-Ingress-conntroler-alb.git
  password: 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
  username: B-O-W